POST http://seriousbusinessincorporated.online/LAMPAPI/AddContact.php HTTP/1.1
content-type: application/json

{
    "FirstName": "Testy",
    "LastName": "Test",
    "Email": "email@email.com",
    "Phone": "0000000000",
    "UserID": "123456" 
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/Login.php HTTP/1.1
content-type: application/json

{
    "login": "username",
    "password": "password"
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/SearchContacts.php HTTP/1.1
content-type: application/json

{
    "userId": 27,
    "firstName": "",
    "lastName": "",
    "phone": "",
    "email": ""
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/DeleteContacts.php HTTP/1.1
content-type: application/json

{
    "userId": 27
}