POST http://seriousbusinessincorporated.online/LAMPAPI/AddContact.php HTTP/1.1
content-type: application/json

{
    "firstName": "j",
    "lastName": "hfkdfiyilh",
    "phoneNumber": "dfsjf",
    "emailAddress": "fjdskfhdsjifuo",
    "userId": "27"
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/GetContacts.php HTTP/1.1
content-type: application/json

{
    "userId": 39
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/UpdateContact.php HTTP/1.1
content-type: application/json

{
    "firstName": "AAAAAj",
    "lastName": "BBBBB",
    "phoneNumber": "CCfdsfdsfdsfsCCCC",
    "emailAddress": "fjsklflsjkdjkgsafsakggkjjjklk",
    "userId": "39",
    "id": "32"
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/DeleteContact.php HTTP/1.1
content-type: application/json

{
    "userId": 30,
    "id": 31
}
###
POST http://seriousbusinessincorporated.online/LAMPAPI/Login.php HTTP/1.1
content-type: application/json

{
    "login": "username",
    "password": "password"
}